# SOURCES
# https://starship.rs/config
# https://starship.rs/presets/nerd-font.html#configuration

# DEBUG via:
# starship explain
# STARSHIP_LOG=trace

"$schema" = 'https://starship.rs/config-schema.json'

# Timeout for commands executed by starship (ms)
command_timeout = 1000

# newline between commands
add_newline = true

# ! opt-in for individual modules (e.g., aws, docker, gcloud, nodejs, python)
# standalone format to get os glyph on ps1 line,
# prompt character below
format = """
$directory$git_branch$git_status$git_commit$fill$python$cmd_duration$terraform
$character
"""

[fill]
symbol = '.'
style = 'fg:7'


# Replace the "❯"
[character]
success_symbol = "[>](green)"
vimcmd_symbol = "[>](yellow)"
error_symbol = "[>](red)"

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = true
format = "[@$hostname](green bold)"
disabled = false

# truncation length works backwards (i.e., cwd > parent > parent ...)
[directory]
truncation_length = 15
truncation_symbol = "…/"
truncate_to_repo = true
style = 'blue'
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
truncation_length = 25
truncation_symbol = ''

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[++\($count\)](green)'

[git_commit]
commit_hash_length = 4

[env_var.SHELL]
variable = "SHELL"
default = "unknown shell"
disabled = true

[cmd_duration]
min_time = 500
format = '[$duration](bold yellow)'

# Show python version starting with venv
[python]
python_binary = [
    "./.venv/bin/python",
    "./venv/bin/python",
    "python3",
    "python",
    "python2",
]
symbol = 'Py '
# pyenv_version_name = true
style = 'blue'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
# format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[aws]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[os]
format = '[$symbol](bold white)'
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
